emojis:
  "<3": "Â§rÂ§câ¤Â§fÂ§r"
  ":noooo:": "ðŸ˜¡"
  ":devious:": "ðŸ˜›"
  ":bruhmm:": "ðŸ˜®"
  ":sleepo:": "ðŸ˜´"
  ":shocked:": "ðŸ˜±"
  ":bedge:": "ðŸ˜µ"
  ":hmm:": "ðŸ™„"
  ":peeposhy:": "ðŸ˜Š"
  ":dinkdonk:": "ðŸ˜—"
  ":awkward:": "ðŸ˜¸"
  ":reallymad:": "ðŸ˜¤"
  ":donowall:": "ðŸ˜©"
  ":letsgo:": "ðŸ˜ˆ"
  ":nerdge:": "ðŸ¤“"
  ":hi:": "ðŸ¥³"